### ISSUE TITLE
Missing license text for test files copied from dotnet-assets

### ISSUE THREAD

**Issue by musicinmybrain** [zip-rs/zip2#132]
**Describe the bug**

Certain files in `tests/data/` are copied from https://github.com/dotnet/runtime-assets.

https://github.com/zip-rs/zip2/blob/102e31113daa5e9553db14c985b1db3f519174a8/tests/data/README.md?plain=1#L1-L6

These are therefore covered by the overall license of that repository, https://github.com/dotnet/runtime-assets/raw/95277f38e68b66f1b48600d90d456c32c9ae0fa2/LICENSE.TXT.

This is [MIT](https://spdx.org/licenses/MIT.html), just like the license of this crate, but the MIT license terms require the copyright and permission notices (i.e., the license text) to be “included in all copies or substantial portions of the Software.”

Therefore, a copy of the license file for `dotnet/runtime-assets`, with the correct copyright statement, should be committed to this repository.

**To Reproduce**

1. Examine https://github.com/zip-rs/zip2/tree/v1.3.0/tests/data
2. Observe that two files are attributed to https://github.com/dotnet/runtime-assets.
3. Observe that no license text is present for these two files.

**Expected behavior**
All required license texts are present for all files.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

A reasonable fix would be to add the contents of https://github.com/dotnet/runtime-assets/raw/95277f38e68b66f1b48600d90d456c32c9ae0fa2/LICENSE.TXT, perhaps converted from CRNL to NL line terminations with `dos2unix` or similar, to a file in `tests/data/`. I suggest `tests/data/LICENSE-dotnet-assets`.

You could additionally append to `tests/data/README.md` something like:

```

See [`LICENSE-dotnet-assets`](./LICENSE-dotnext-assets), which contains the text from https://github.com/dotnet/runtime-assets/raw/95277f38e68b66f1b48600d90d456c32c9ae0fa2/LICENSE.TXT.
```

I would be happy to open a trivial PR to do this, but I am not willing to set up GPG commit signing just for that purpose, so I’m just filing this issue and moving on instead.

**Comment by Pr0methean** [comment]
Fixed. There's actually one other file, `tests/data/lin-ub_iwd-v11.zip` that was provided in a pull request, and the authors aren't credited so I don't know who owns it. It's a version of "Unfinished Business for Icewind Dale", but it would be nice to know whether it actually contained any code or assets that Interplay owns. If you happen to be able to find out, please feel free to open another issue!

**Comment by musicinmybrain** [comment]
I appreciate the follow-up, but it seems like the new files `LICENSE.deflate64.zip.txt` and `LICENSE.binary.wmv.txt` are empty. Am I missing anything?

**Comment by musicinmybrain** [comment]
> Fixed. There's actually one other file, `tests/data/lin-ub_iwd-v11.zip` that was provided in a pull request, and the authors aren't credited so I don't know who owns it. It's a version of "Unfinished Business for Icewind Dale", so if anyone claims copyright on it it'll be Interplay Entertainment; but I don't know whether any of their code or art is present so that such a claim would be legitimate. If you happen to be able to find out, please feel free to open another issue!

It looks like `tests/data/lin-ub_iwd-v11.zip` is exactly the release archive from https://github.com/Gibberlings3/iwd_unfinished_business/releases/tag/v11. A quick survey doesn’t reveal any obvious game content from the commercial Icewind Dale game in this mod—although it is hard to be entirely certain—but on the other hand, there is no declared license for the original content in the mod, so it could still be problematic on that basis alone.

**Comment by Pr0methean** [comment]
Thanks; I've updated the empty files (still not sure how they ended up being committed empty) and, in the case of the Icewind Dale mod, added a brief attribution and a copy of the project's own relevant notices.
