### ISSUE TITLE
Non-script source file src/result.rs should not be executable

### ISSUE THREAD

**Issue by musicinmybrain** [zip-rs/zip2#133]
**Describe the bug**

The source file `src/result.rs` has the executable bit set in its filesystem permissions, but it is not a script.

**To Reproduce**
1. Examine https://github.com/zip-rs/zip2/blob/v1.3.0/src/result.rs.
2. Observe that the GitHub UI describes it as an “`Executable File`,” but that it is a Rust source rather than an interpreted script.

**Expected behavior**
Non-script sources should not have executable permissions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
In particular, executable Rust sources can cause problems with Linux distribution packaging because `#![…]` directives look like shebang lines, and this can confuse automation.

**Comment by Pr0methean** [comment]
Fixed.

**Comment by musicinmybrain** [comment]
Thanks!
