### ISSUE TITLE
Why `impl TryInto<NaiveDateTime> for DateTime` instead of `impl TryFrom<DateTime> for NaiveDateTime`?

### ISSUE THREAD

**Issue by sorairolake** [zip-rs/zip2#136]
https://github.com/zip-rs/zip2/blob/4b295d3d5a20a1a210c9c6380b57f0e1c9b42dce/src/types.rs#L110-L122

Why does this implement `TryInto<NaiveDateTime> for DateTime` instead of `TryFrom<DateTime> for NaiveDateTime`?

**Comment by Pr0methean** [comment]
I was unfamiliar with the convention that favors TryFrom as the explicitly-implemented trait. Fixed in 3afe549161cf769f845e50f8d8ec306bc76a8240.
