### ISSUE TITLE
`No valid central directory found` on Linux

### ISSUE THREAD

**Issue by russellbanks** [zip-rs/zip2#239]
**Describe the bug**
Some zip files return an `invalid Zip archive: No valid central directory found` error. This occurs only on Linux and not on Windows.

- https://github.com/russellbanks/Komac/issues/770
- https://github.com/sxyazi/yazi/issues/1567

**To Reproduce**
The user uses https://td.telegram.org/tx64/tportable-x64.5.4.1.zip.

Open this using `ZipArchive::new()`.

**Comment by davemollen** [comment]
I seem to have the same issue on mac.

**Comment by devklick** [comment]
I experienced this error after I had created the archive with then tried to use it as a ZipArchive, e.g.
```rs
let file = File::create($archive_path_buff).unwrap();
zip::ZipArchive::new(&file).unwrap();
```
I think the problem is something to do with the file being opened in write-only mode. Creating the file in read-write mode solved it for me, e.g:
```rs
let file = File::options()
    .read(true) // omitting this reproduces the error
    .write(true)
    .create(true)
    .open(&archive_path_buff);

zip::ZipArchive::new(&file).unwrap();
```

Try specifying the `.read(true)` option when opening the file.

**Comment by russellbanks** [comment]
> Try specifying the `.read(true)` option when opening the file.

I use [tempfile](https://github.com/Stebalien/tempfile) which creates files in read-write mode.

**Comment by devklick** [comment]
I've followed your reproduce steps (without using tempfile), and it works as expected:
```rs
let file = File::open("/home/user/Downloads/tportable-x64.5.4.1.zip").unwrap();

let result = match ZipArchive::new(file) {
    Err(e) => e.to_string(),
    Ok(_) => "Success".to_owned(),
};

println!("{result}"); // Success
```
Which makes me wonder if it's perhaps an issue with the way that either your package or tempfile creates the temporary zip file.

Are you able to provide an example that reproduces this error?

**Comment by russellbanks** [comment]
> Which makes me wonder if it's perhaps an issue with the way that either your package or tempfile creates the temporary zip file.

After investigating, I found that the issue for me was because the file (that I download in my application) hadn't fully finished being written before it was memory mapped and passed to ZipArchive. This makes sense as different operating systems will have different ways of writing changes to a file, and that this issue only appeared with zips because the central directory will need to be checked for at the end of the file.

Tokio File docs:
> A file will not be closed immediately when it goes out of scope if there are any IO operations that have not yet completed. To ensure that a file is closed immediately when it is dropped, you should call [flush](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWriteExt.html#method.flush) before dropping it. Note that this does not ensure that the file has been fully written to disk; the operating system might keep the changes around in an in-memory buffer. See the [sync_all](https://docs.rs/tokio/latest/tokio/fs/struct.File.html#method.sync_all) method for telling the OS to write the data to disk.

The fix for me was calling `file.flush()` and `file.sync_all()` after downloading the file to ensure that ZipArchive retrieved the completed file.

https://github.com/russellbanks/Komac/commit/e1d1b91b26528ac66c077d07bf7d1b934cf90bf7

**Comment by bluenote10** [comment]
I definitely think that there is a real bug/regression here. I have a zip file, and I'm using the following minimal reproduction code:

```rust
fn main() {
    let file_path = std::path::Path::new("/tmp/test.zip");
    let file = std::fs::File::open(file_path).unwrap();
    let zip = zip::ZipArchive::new(file).unwrap();
    println!("Number of files: {}", zip.len());
}
```

This code works if I use zip version 1.1.4, but crashes with version 2.0.0 and later (including 2.2.0). In my case it has nothing to do with the file not being flushed, or write-only mode.

Unfortunately I cannot share this particular zip file I'm experiencing it with. Other zip files work fine, i.e., it is not a general problem. My suspicion is that it has something to do with either having _a lot_ of files in the zip file (mine has 140k files) or with broken unicode file names (mine contains filenames that apparently have been encoded with some legacy Windows code pages). I need to figure out a way to come up with a minimal reproducible example.

**Comment by bluenote10** [comment]
I have bisected this issue: The last commit that still works for me is 1e118199, and 88b4ae30b4f65bd41345990c3c7466ca573bddab is the first failing one. However it is failing with a different error (`InvalidArchive("CRC32 checksum failed on Unicode extra field")`) than later versions (`
No valid central directory found`). This suggests that the issue is indeed caused by non-unicode file names. I don't think ZIP requires entries to be valid unicode, i.e., reading such an archive should not fail.

I hope I'll find some time to generate a small reproduction zip file.
