### ISSUE TITLE
Zip package created on Windows will generate messy up files after unpack on MacOS 

### ISSUE THREAD

**Issue by ikey4u** [zip-rs/zip2#242]
**Describe the bug**

Zip a directory to create a zip package on Windows will not unzip correctly on MacOS, lets say you have a directory on Windows looks like:
```
mydir/
    +-- folder/
        +-- subfolder/
             +-- test.txt
```

Use this library (version 2.2) to zip `mydir` on Windows, and unzip it on MacOS you will get following directory:
```
$ unzip mydir.zip -d mydir
Archive:  mydir.zip
   skipping: folder\subfolder\test.txt  unsupported compression method 93
   creating: mydir/folder/
   creating: mydir/folder\subfolder/

$ tree mydir
mydir
├── folder
└── folder\\subfolder

```
**To Reproduce**

It is a little tedious to reproduce, but you can copy code from [here](https://github.com/ikey4u/snippet/blob/master/src/zip.rs) to create a zip package such as:

```
 let d = std::path::Path::new(r#"D:\mydir"#);
 let b = snippet::zip::pack(&d)?;
 let mut f = File::create("mydir.zip")?;
 f.write_all(&b)?;
```
Then you can test the created `mydir.zip`.

**Comment by qclucky7** [comment]
Same problem, how did you solve it?

**Comment by ikey4u** [comment]
> Same problem, how did you solve it?

Solution: https://github.com/ikey4u/snippet/commit/6f8bb22872b64bf582792f4d614bf5f19e626ee4

@qclucky7
