### ISSUE TITLE
Missing release tags in repository

### ISSUE THREAD

**Issue by jirutka** [zip-rs/zip2#31]
Please add release tags corresponding to versions on crates.io. Ideally, the crate should be published automatically via CI based on the release tags.

**Comment by Pr0methean** [comment]
If I were going to do that, how would I recover from possible failures in `cargo publish`?

**Comment by Pr0methean** [comment]
I'm testing a CI setup that will do this for future versions, and have manually added tags for already-released versions 0.10.3 and newer.
