### ISSUE TITLE
The `deflate` and `deflate-miniz` features are the same?

### ISSUE THREAD

**Issue by torokati44** [zip-rs/zip2#35]
I have an observation about these lines: https://github.com/Pr0methean/zip/blob/75691456272cd43d4b08210808af9d8756406851/Cargo.toml#L57-L58

The `default` feature of `flate2` is `rust_backend`: https://github.com/rust-lang/flate2-rs/blob/ae784978ff22dea373cf820b3ef5fbc6e948de3f/Cargo.toml#L34

I suppose, since this: https://github.com/rust-lang/flate2-rs/pull/216

So, the `deflate` and `deflate-miniz` features might be identical now? :thinking:

(Somewhat related: #107)

**Comment by Pr0methean** [comment]
Looks like they are indeed identical, and there's no longer a `miniz.c` back end.

**Comment by Pr0methean** [comment]
Update: I've now restored the feature, but documented that it is deprecated in version 1.1.2.
